name: CI
on:
  push:
    branches:
      - main
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - uses: actions/setup-node@v1
        with:
          node-version: 15.x
      - name: Install dependencies
        run: npm install
      - name: Install dependencies(2)
        run: yarn add ci-info

      - name: Create build
        run: npx nx build react-native-expo
      - name: Create token
        run: echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" > ~/.npmrc
      - name: Create token
        run: cat ~/.npmrc
      - name: Publish repo
        run: npm publish
        working-directory: ./dist/packages/react-native-expo
        env:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
 